name: Python

on:
  push:
    tags:
       - 'v*'

jobs:
  #macos:
  #  runs-on: macos-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - uses: actions/setup-python@v2
  #      with:
  #        python-version: 3.9
  #        architecture: x64
  #    - name: Install Rust toolchain
  #      uses: actions-rs/toolchain@v1
  #      with:
  #        toolchain: nightly
  #        profile: minimal
  #        default: true
  #    - name: Build wheels - x86_64
  #      uses: PyO3/maturin-action@v1
  #      with:
  #        target: x86_64
  #        args: --release --out dist --sdist -m Cargo.toml -F python
  #    - name: Install built wheel - x86_64
  #      run: |
  #        pip install reasonable --no-index --find-links dist --force-reinstall
  #        python -c "import reasonable"
  #    - name: Build wheels - universal2
  #      uses: PyO3/maturin-action@v1
  #      with:
  #        args: --release --universal2 --out dist -m Cargo.toml -F python
  #    - name: Install built wheel - universal2
  #      run: |
  #        pip install reasonable --no-index --find-links dist --force-reinstall
  #        python -c "import reasonable"
  #    - name: Upload wheels
  #      uses: actions/upload-artifact@v3
  #      with:
  #        name: wheels
  #        path: dist
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          manylinux: auto
          args: --release --out dist -m Cargo.toml -F python
      - name: Install built wheel
        if: matrix.target == 'x86_64'
        run: |
          pip install reasonable --no-index --find-links dist --force-reinstall
          python -c "import reasonable"
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: target/wheels
