name: manylinux2014
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
jobs:
  manylinux2014:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python: [
          { version: '3.7', abi: 'cp37-cp37m' },
          { version: '3.8', abi: 'cp38-cp38' },
          { version: '3.9', abi: 'cp39-cp39' },
          { version: '3.10', abi: 'cp310-cp310' },
          { version: '3.11', abi: 'cp311-cp311' },
        ]
    container:
      image: quay.io/pypa/manylinux2014_x86_64:latest
      options: --user 0
    env:
      PATH: /root/.local/bin/:/root/.cargo/bin:/github/home/.local/bin:/github/home/.cargo/bin:/opt/python/${{ matrix.python.abi }}/bin:/opt/rh/devtoolset-10/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    steps:
    - name: install poetry
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: "1.1.15"
    - run: curl https://sh.rustup.rs -sSf | sh -s -- --profile minimal -y
    - uses: actions/checkout@v2
    - run: poetry install
    - run: poetry run maturin build --release --strip -F python --compatibility manylinux2014 --interpreter python${{ matrix.python.version }}
    - run: poetry run pip install target/wheels/reasonable*.whl
    - run: poetry run maturin publish --no-sdist -m Cargo.toml -u __token__ -p ${{ secrets.PYPI_API_TOKEN }} -F python
      #- name: deploy
      #  run: peotry run maturin build --release --strip --features=python --compatibility manylinux2014 --interpreter python${{ matrix.python.version }}
      #  env:
      #    MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      #- uses: pypa/gh-action-pypi-publish@release/v1
      #  with:
      #    user: __token__
      #    password: ${{ secrets.PYPI_API_TOKEN }}
      #    packages_dir: target/wheels
      #- uses: softprops/action-gh-release@v1
      #  with:
      #    files: target/wheels/*.tar.gz
